import nodemailer from "nodemailer";
import dns from "dns";
import { promisify } from "util";

const dnsLookup = promisify(dns.lookup);

async function resolveIPv4(hostname) {
  const { address } = await dnsLookup(hostname, { family: 4 });
  return address;
}

async function createTransporter() {
  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASSWORD;

  if (!user) {
    throw new Error("Missing GMAIL_USER");
  }
  if (!pass) {
    throw new Error("Missing GMAIL_APP_PASSWORD");
  }

  const port = Number.parseInt(process.env.GMAIL_SMTP_PORT || "465", 10);
  const secure = port === 465;

  // Force IPv4 by resolving smtp.gmail.com to an IPv4 address before connecting.
  // Nodemailer's family/socketOptions don't reliably prevent IPv6 connections.
  const ipv4Host = await resolveIPv4("smtp.gmail.com");
  console.log(`Gmail SMTP resolved smtp.gmail.com -> ${ipv4Host} port=${port} secure=${String(secure)}`);

  const transporter = nodemailer.createTransport({
    host: ipv4Host,
    port,
    secure,
    auth: {
      user,
      pass,
    },
    tls: {
      servername: "smtp.gmail.com",
    },
    connectionTimeout: 20_000,
    greetingTimeout: 20_000,
    socketTimeout: 30_000,
  });

  return transporter;
}

export async function sendPriceAlertEmail(toEmail, assetSymbol, thresholdPrice, currentPrice) {
  if (!toEmail) {
    throw new Error("Missing toEmail");
  }
  if (!assetSymbol) {
    throw new Error("Missing assetSymbol");
  }

  const transporter = await createTransporter();

  const subject = "Price Alert Triggered";
  const text = `The asset ${assetSymbol} has crossed your alert threshold.\n\nThreshold: ${thresholdPrice}\nCurrent price: ${currentPrice}\n\nThis alert was generated by your price alert settings.`;

  const info = await transporter.sendMail({
    from: process.env.GMAIL_USER,
    to: toEmail,
    subject,
    text,
  });

  return info;
}
