import nodemailer from "nodemailer";

function createTransporter() {
  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASSWORD;

  if (!user) {
    throw new Error("Missing GMAIL_USER");
  }
  if (!pass) {
    throw new Error("Missing GMAIL_APP_PASSWORD");
  }

  const port = Number.parseInt(process.env.GMAIL_SMTP_PORT || "465", 10);
  const secure = port === 465;
  const family = process.env.GMAIL_SMTP_FAMILY ? Number.parseInt(process.env.GMAIL_SMTP_FAMILY, 10) : 4;

  const transporter = nodemailer.createTransport({
    service: "gmail",
    host: "smtp.gmail.com",
    port,
    secure,
    auth: {
      user,
      pass,
    },
    tls: {
      servername: "smtp.gmail.com",
    },
    connectionTimeout: 20_000,
    greetingTimeout: 20_000,
    socketTimeout: 30_000,
    ...(Number.isFinite(family) ? { family } : {}),
  });

  console.log(`Gmail SMTP configured host=smtp.gmail.com port=${port} secure=${String(secure)} family=${String(family)}`);
  return transporter;
}

export async function sendPriceAlertEmail(toEmail, assetSymbol, thresholdPrice, currentPrice) {
  if (!toEmail) {
    throw new Error("Missing toEmail");
  }
  if (!assetSymbol) {
    throw new Error("Missing assetSymbol");
  }

  const transporter = createTransporter();

  const subject = "Price Alert Triggered";
  const text = `The asset ${assetSymbol} has crossed your alert threshold.\n\nThreshold: ${thresholdPrice}\nCurrent price: ${currentPrice}\n\nThis alert was generated by your price alert settings.`;

  const info = await transporter.sendMail({
    from: process.env.GMAIL_USER,
    to: toEmail,
    subject,
    text,
  });

  return info;
}
