import nodemailer from "nodemailer";

function createTransporter() {
  const user = process.env.GMAIL_USER;
  const pass = process.env.GMAIL_APP_PASSWORD;

  if (!user) {
    throw new Error("Missing GMAIL_USER");
  }
  if (!pass) {
    throw new Error("Missing GMAIL_APP_PASSWORD");
  }

  return nodemailer.createTransport({
    host: "smtp.gmail.com",
    port: 587,
    secure: false,
    auth: {
      user,
      pass,
    },
  });
}

export async function sendPriceAlertEmail(toEmail, assetSymbol, thresholdPrice, currentPrice) {
  if (!toEmail) {
    throw new Error("Missing toEmail");
  }
  if (!assetSymbol) {
    throw new Error("Missing assetSymbol");
  }

  const transporter = createTransporter();

  const subject = "Price Alert Triggered";
  const text = `The asset ${assetSymbol} has crossed your alert threshold.\n\nThreshold: ${thresholdPrice}\nCurrent price: ${currentPrice}\n\nThis alert was generated by your price alert settings.`;

  const info = await transporter.sendMail({
    from: process.env.GMAIL_USER,
    to: toEmail,
    subject,
    text,
  });

  return info;
}
