import sgMail from "@sendgrid/mail";

type Env = {
  SENDGRID_API_KEY?: string;
  ALERT_FROM_EMAIL?: string;
  ALERT_FROM_NAME?: string;
};

type EnvLike = Env & Record<string, string | undefined>;

function getSendGridConfig(env: EnvLike = process.env as EnvLike) {
  const apiKey = env.SENDGRID_API_KEY;
  if (!apiKey) {
    throw new Error("Missing SENDGRID_API_KEY");
  }

  const fromEmail = env.ALERT_FROM_EMAIL;
  if (!fromEmail) {
    throw new Error("Missing ALERT_FROM_EMAIL");
  }

  const fromName = env.ALERT_FROM_NAME;

  return { apiKey, fromEmail, fromName };
}

export async function sendPriceAlertEmail(params: {
  toEmail: string;
  assetSymbol: string;
  thresholdPrice: number;
  currentPrice: number;
  env?: EnvLike;
}): Promise<void> {
  const env = (params.env ?? (process.env as EnvLike)) as EnvLike;
  const { apiKey, fromEmail, fromName } = getSendGridConfig(env);

  if (!params.toEmail) {
    throw new Error("Missing toEmail");
  }
  if (!params.assetSymbol) {
    throw new Error("Missing assetSymbol");
  }

  const subject = "Price Alert Triggered";
  const text = `The asset ${params.assetSymbol} has crossed your alert threshold.\n\nThreshold: ${params.thresholdPrice}\nCurrent price: ${params.currentPrice}\n\nThis alert was generated by your price alert settings.`;

  sgMail.setApiKey(apiKey);

  const from = fromName ? { email: fromEmail, name: fromName } : { email: fromEmail };

  const [resp] = await sgMail.send({
    to: params.toEmail,
    from,
    subject,
    text,
  });

  const statusCode = (resp as any)?.statusCode;
  const headers = (resp as any)?.headers;
  console.log(
    `SendGrid send ok to=${params.toEmail} status=${String(statusCode ?? "")} x-message-id=${String(headers?.["x-message-id"] ?? "")}`,
  );
}
